'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WonderPrints_Project.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0029BFD5_7199_40FA_8975_D21B51FC02FA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0029BFD5-7199-40FA-8975-D21B51FC02FA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _02806D13_6304_4030_888B_AEC4D0FDE236() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("02806D13-6304-4030-888B-AEC4D0FDE236", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _176388B1_E173_414A_8227_369CA66508C1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("176388B1-E173-414A-8227-369CA66508C1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2EB4D9C1_798F_40A0_A920_D9C16D7904B7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2EB4D9C1-798F-40A0-A920-D9C16D7904B7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3525D5E1_129A_4FD7_9A4F_0E173A5AED8F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3525D5E1-129A-4FD7-9A4F-0E173A5AED8F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _470F6A98_68F9_44D0_90E6_23E3EBF9718A() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("470F6A98-68F9-44D0-90E6-23E3EBF9718A", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4871F58C_32C0_47E5_96DD_2FDBC3158CDF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4871F58C-32C0-47E5-96DD-2FDBC3158CDF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5717CF14_E677_4169_8E39_23EA3F7D097A() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5717CF14-E677-4169-8E39-23EA3F7D097A", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5C25B558_24A4_4367_940D_316333DE0D8A() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5C25B558-24A4-4367-940D-316333DE0D8A", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _6C9C15E0_9C87_4B63_97A3_CAE4FC7E6CA4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6C9C15E0-9C87-4B63-97A3-CAE4FC7E6CA4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _6C9C15E0_9C87_4B63_97A3_CAE4FC7E6CA41() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6C9C15E0-9C87-4B63-97A3-CAE4FC7E6CA41", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _77F9CEA3_D5CA_4C73_83BB_0A93AFE3ACA9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("77F9CEA3-D5CA-4C73-83BB-0A93AFE3ACA9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _88910174_FC87_456A_AF10_8DFD22AEC217() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("88910174-FC87-456A-AF10-8DFD22AEC217", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _889B44BE_6F27_48AD_BEE3_2589035A673E() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("889B44BE-6F27-48AD-BEE3-2589035A673E", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _8996C447_B9FD_4968_958A_48153AFBFFEB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8996C447-B9FD-4968-958A-48153AFBFFEB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9621E114_A55B_4D01_A85C_7B5BEFDAE4CD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9621E114-A55B-4D01-A85C-7B5BEFDAE4CD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property A61064D5_167B_407B_9B07_B6B0D8115ED9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("A61064D5-167B-407B-9B07-B6B0D8115ED9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property add_to_cart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add-to-cart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property B0605E8E_000C_480B_A80D_819EE675D824() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("B0605E8E-000C-480B-A80D-819EE675D824", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property B28DE987_24C1_44BA_8EAF_929E55C16FEE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("B28DE987-24C1-44BA-8EAF-929E55C16FEE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property B4D1DC71_F7A0_4E19_9B07_038A9DCE06A9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("B4D1DC71-F7A0-4E19-9B07-038A9DCE06A9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D648B386_2878_443F_B391_537D42E4367E() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D648B386-2878-443F-B391-537D42E4367E", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D6A68D3E_61AB_49A6_8B4B_DC1E4ADE91C1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D6A68D3E-61AB-49A6-8B4B-DC1E4ADE91C1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property F4AE8C52_0137_4DEC_BE63_C4A305675B4C() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("F4AE8C52-0137-4DEC-BE63-C4A305675B4C", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property F88CBE36_E9A1_467B_9025_C604BFA4C794() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("F88CBE36-E9A1-467B-9025-C604BFA4C794", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FE3B2F9F_FBED_4680_A1CC_4B9D1B9DE8E1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FE3B2F9F-FBED-4680-A1CC-4B9D1B9DE8E1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hoodie() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hoodie", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hoodie1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hoodie1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hoodie2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hoodie2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hoodie3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hoodie3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hoodie4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hoodie4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hoodie5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hoodie5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMG_20230724_230950() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMG_20230724_230950", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMG_20230724_231022() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMG_20230724_231022", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMG_20230724_231531() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMG_20230724_231531", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMG_20230724_231544() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMG_20230724_231544", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMG_20230724_231555() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMG_20230724_231555", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMG_20230724_231609() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMG_20230724_231609", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMG_20230724_231622() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMG_20230724_231622", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMG_20230724_231828() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMG_20230724_231828", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMG_20230724_231841() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMG_20230724_231841", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMG_20230724_231856() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMG_20230724_231856", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMG_20230724_231908() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMG_20230724_231908", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jungwonwf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jungwonwf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property login() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property main_page() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main page", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pagmamahal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pagmamahal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pagmamahal1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pagmamahal1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shirt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shirt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shirt1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shirt1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shirt2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shirt2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shirt3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shirt3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property totebag1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("totebag1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property user() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wonderprints_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wonderprints logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wonderprints_logo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wonderprints logo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wonderprints_logo2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wonderprints logo2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wonderprints_logo3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wonderprints logo3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
